version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - currency-compose-network
    
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - currency-compose-network
    
  netflix-eureka-naming-server:
    image: kiranluitel/microservice-project:netflix-eureka-naming-server
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network
    
  netflix-zuul-api-gateway-server:
    image: kiranluitel/microservice-project:netflix-zuul-api-gateway-server
    ports:
      - "8765:8765"
    restart: always
    networks:
      - currency-compose-network
    depends_on:
      - netflix-eureka-naming-server
      - currency-exchange-service
      - currency-conversion-service
      - rabbitmq
      - zipkin-server
    environment:
      EUREKA_SERVER: netflix-eureka-naming-server
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    
  currency-exchange-service:
    image: kiranluitel/microservice-project:currency-exchange-service
    ports:
      - "8000:8000"
    restart: always
    networks:
      - currency-compose-network
    environment:
      EUREKA_SERVER: netflix-eureka-naming-server
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - netflix-eureka-naming-server
      - zipkin-server
    
  currency-conversion-service:
    image: kiranluitel/microservice-project:currency-conversion-service
    ports:
      - "8100:8100"
    restart: always
    networks:
      - currency-compose-network
    environment:
      EUREKA_SERVER: netflix-eureka-naming-server
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - currency-exchange-service
      - netflix-eureka-naming-server
      - zipkin-server
            
networks:
  currency-compose-network:
        
